versiion: "3.9"
services: 
  web:
    build: .
    ports: 
      -"8080:8080"
      environment:
        MONGODB_URI=mongodb+srv://jokesdb:jokesdb@joke.kxki9.mongodb.net/myFirstDatabase?retryWrites=true&w=majority